name: Assign to project

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: timroes/assign-to-project-action@0.0.8
          with:
            owner: airbytehq
            token: ${{ secrets.PAT }}
            projects: |
              documentation=8
