name: CI test

on:
  push:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - name: Build step
          run: |
            echo "Building ..."
            echo "oh no failed..."
            exit 1
        - if: failure()
          run: |
            echo "::error::The build was what failed!"
        - name: Test step
          run: |
            echo "testing now"
            echo "something"
        - if: failure()
          run: |
            echo "::error::The test step failed!"
