name: Assign to project

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: timroes/assign-to-project-action@0.0.6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            projects: |
              documentation=1
